// ─── DONNÉES STATIQUES ─────────────────────────────────

const FLAGS = {
  'Mexique':'🇲🇽','Afrique du Sud':'🇿🇦','Corée du Sud':'🇰🇷','Rép. Tchèque':'🇨🇿',
  'Canada':'🇨🇦','Qatar':'🇶🇦','Bosnie-Herzégovine':'🇧🇦','Suisse':'🇨🇭',
  'Brésil':'🇧🇷','Écosse':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Maroc':'🇲🇦','Haïti':'🇭🇹',
  'États-Unis':'🇺🇸','Türkiye':'🇹🇷','Paraguay':'🇵🇾','Australie':'🇦🇺',
  'Allemagne':'🇩🇪','Équateur':'🇪🇨','Côte d\'Ivoire':'🇨🇮','Curaçao':'🇨🇼',
  'Pays-Bas':'🇳🇱','Tunisie':'🇹🇳','Japon':'🇯🇵','Suède':'🇸🇪',
  'Belgique':'🇧🇪','Nouvelle-Zélande':'🇳🇿','Égypte':'🇪🇬','Iran':'🇮🇷',
  'Espagne':'🇪🇸','Cap-Vert':'🇨🇻','Uruguay':'🇺🇾','Arabie Saoudite':'🇸🇦',
  'France':'🇫🇷','Irak':'🇮🇶','Sénégal':'🇸🇳','Norvège':'🇳🇴',
  'Argentine':'🇦🇷','Jordanie':'🇯🇴','Algérie':'🇩🇿','Autriche':'🇦🇹',
  'Portugal':'🇵🇹','RD Congo':'🇨🇩','Colombie':'🇨🇴','Ouzbékistan':'🇺🇿',
  'Angleterre':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Panama':'🇵🇦','Croatie':'🇭🇷','Ghana':'🇬🇭',
};

const GROUP_COLORS = {
  A:'#e74c3c',B:'#e67e22',C:'#f1c40f',D:'#2ecc71',
  E:'#1abc9c',F:'#3498db',G:'#9b59b6',H:'#e91e8c',
  I:'#ff5722',J:'#4caf50',K:'#00bcd4',L:'#ff9800',
  'KO':'#7c3aed'
};

const FEATURED = [
  'France vs Sénégal','Argentine vs Algérie','Portugal vs Colombie',
  'Brésil vs Maroc','Espagne vs Uruguay','Pays-Bas vs Japon',
  'Angleterre vs Croatie','États-Unis vs Turquie','Mexique vs Afrique du Sud'
];

const MATCHES = [
  {id:1, group:'A',date:'11 juin',day:'Jeu',home:'Mexique',      away:'Afrique du Sud',   stadium:'Estadio Azteca',           city:'Mexico City',  featured:true, label:'OUVERTURE', time:'15h00'},
  {id:2, group:'A',date:'11 juin',day:'Jeu',home:'Corée du Sud', away:'Rép. Tchèque',         stadium:'Estadio Akron',            city:'Guadalajara', time:'22h00'},
  {id:3, group:'A',date:'18 juin',day:'Jeu',home:'Rép. Tchèque',     away:'Afrique du Sud',   stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'15h00'},
  {id:4, group:'A',date:'18 juin',day:'Jeu',home:'Mexique',      away:'Corée du Sud',     stadium:'Estadio Akron',            city:'Guadalajara', time:'21h00'},
  {id:5, group:'A',date:'24 juin',day:'Mer',home:'Rép. Tchèque',     away:'Mexique',          stadium:'Estadio Azteca',           city:'Mexico City', time:'15h00'},
  {id:6, group:'A',date:'24 juin',day:'Mer',home:'Afrique du Sud',away:'Corée du Sud',    stadium:'Estadio BBVA',             city:'Monterrey', time:'18h00'},
  {id:7, group:'B',date:'12 juin',day:'Ven',home:'Canada',       away:'Bosnie-Herzégovine',stadium:'BMO Field',               city:'Toronto', time:'21h00'},
  {id:8, group:'B',date:'13 juin',day:'Sam',home:'Qatar',        away:'Suisse',           stadium:'Levi\'s Stadium',          city:'San Francisco', time:'12h00'},
  {id:9, group:'B',date:'18 juin',day:'Jeu',home:'Suisse',       away:'Bosnie-Herzégovine',stadium:'SoFi Stadium',            city:'Los Angeles', time:'13h00'},
  {id:10,group:'B',date:'18 juin',day:'Jeu',home:'Canada',       away:'Qatar',            stadium:'BC Place',                 city:'Vancouver', time:'16h00'},
  {id:11,group:'B',date:'24 juin',day:'Mer',home:'Suisse',       away:'Canada',           stadium:'BC Place',                 city:'Vancouver', time:'19h00'},
  {id:12,group:'B',date:'24 juin',day:'Mer',home:'Bosnie-Herzégovine',away:'Qatar',       stadium:'Lumen Field',              city:'Seattle', time:'22h00'},
  {id:13,group:'C',date:'13 juin',day:'Sam',home:'Brésil',       away:'Maroc',            stadium:'MetLife Stadium',          city:'New York',     featured:true, time:'12h00'},
  {id:14,group:'C',date:'13 juin',day:'Sam',home:'Haïti',        away:'Écosse',           stadium:'Gillette Stadium',         city:'Boston', time:'21h00'},
  {id:15,group:'C',date:'19 juin',day:'Ven',home:'Écosse',       away:'Maroc',            stadium:'Gillette Stadium',         city:'Boston', time:'18h00'},
  {id:16,group:'C',date:'19 juin',day:'Ven',home:'Brésil',       away:'Haïti',            stadium:'Lincoln Financial Field',  city:'Philadelphie', featured:true, time:'20h30'},
  {id:17,group:'C',date:'24 juin',day:'Mer',home:'Écosse',       away:'Brésil',           stadium:'Hard Rock Stadium',        city:'Miami', time:'15h00'},
  {id:18,group:'C',date:'24 juin',day:'Mer',home:'Maroc',        away:'Haïti',            stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'18h00'},
  {id:19,group:'D',date:'12 juin',day:'Ven',home:'États-Unis',   away:'Paraguay',         stadium:'SoFi Stadium',             city:'Los Angeles',  featured:true, time:'21h00'},
  {id:20,group:'D',date:'13 juin',day:'Sam',home:'Australie',    away:'Türkiye',          stadium:'BC Place',                 city:'Vancouver', time:'00h00'},
  {id:21,group:'D',date:'19 juin',day:'Ven',home:'Türkiye',      away:'Paraguay',         stadium:'Levi\'s Stadium',          city:'San Francisco', time:'13h00'},
  {id:22,group:'D',date:'19 juin',day:'Ven',home:'États-Unis',   away:'Australie',        stadium:'Lumen Field',              city:'Seattle', time:'16h00'},
  {id:23,group:'D',date:'25 juin',day:'Mer',home:'Türkiye',      away:'États-Unis',       stadium:'SoFi Stadium',             city:'Los Angeles', time:'19h00'},
  {id:24,group:'D',date:'25 juin',day:'Mer',home:'Paraguay',     away:'Australie',        stadium:'Levi\'s Stadium',          city:'San Francisco', time:'22h00'},
  {id:25,group:'E',date:'14 juin',day:'Dim',home:'Allemagne',    away:'Curaçao',          stadium:'NRG Stadium',              city:'Houston', time:'12h00'},
  {id:26,group:'E',date:'14 juin',day:'Dim',home:'Côte d\'Ivoire',away:'Équateur',        stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'15h00'},
  {id:27,group:'E',date:'20 juin',day:'Sam',home:'Allemagne',    away:'Côte d\'Ivoire',   stadium:'BMO Field',                city:'Toronto', time:'18h00'},
  {id:28,group:'E',date:'20 juin',day:'Sam',home:'Équateur',     away:'Curaçao',          stadium:'Arrowhead Stadium',        city:'Kansas City', time:'21h00'},
  {id:29,group:'E',date:'25 juin',day:'Jeu',home:'Curaçao',      away:'Côte d\'Ivoire',   stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'15h00'},
  {id:30,group:'E',date:'25 juin',day:'Jeu',home:'Équateur',     away:'Allemagne',        stadium:'MetLife Stadium',          city:'New York', time:'18h00'},
  {id:31,group:'F',date:'14 juin',day:'Dim',home:'Pays-Bas',     away:'Japon',            stadium:'AT&T Stadium',             city:'Dallas',       featured:true, time:'20h30'},
  {id:32,group:'F',date:'14 juin',day:'Dim',home:'Suède',        away:'Tunisie',          stadium:'Estadio BBVA',             city:'Monterrey', time:'23h00'},
  {id:33,group:'F',date:'20 juin',day:'Sam',home:'Pays-Bas',     away:'Suède',            stadium:'NRG Stadium',              city:'Houston', time:'13h00'},
  {id:34,group:'F',date:'20 juin',day:'Sam',home:'Tunisie',      away:'Japon',            stadium:'Estadio BBVA',             city:'Monterrey', time:'16h00'},
  {id:35,group:'F',date:'25 juin',day:'Jeu',home:'Japon',        away:'Suède',            stadium:'AT&T Stadium',             city:'Dallas', time:'20h00'},
  {id:36,group:'F',date:'25 juin',day:'Jeu',home:'Tunisie',      away:'Pays-Bas',         stadium:'Arrowhead Stadium',        city:'Kansas City', time:'00h00'},
  {id:37,group:'G',date:'15 juin',day:'Lun',home:'Belgique',     away:'Égypte',           stadium:'Lumen Field',              city:'Seattle', time:'12h00'},
  {id:38,group:'G',date:'15 juin',day:'Lun',home:'Iran',         away:'Nouvelle-Zélande', stadium:'SoFi Stadium',             city:'Los Angeles', time:'15h00'},
  {id:39,group:'G',date:'21 juin',day:'Dim',home:'Belgique',     away:'Iran',             stadium:'SoFi Stadium',             city:'Los Angeles', time:'18h00'},
  {id:40,group:'G',date:'21 juin',day:'Dim',home:'Nouvelle-Zélande',away:'Égypte',        stadium:'BC Place',                 city:'Vancouver', time:'21h00'},
  {id:41,group:'G',date:'26 juin',day:'Ven',home:'Égypte',       away:'Iran',             stadium:'Lumen Field',              city:'Seattle', time:'13h00'},
  {id:42,group:'G',date:'26 juin',day:'Ven',home:'Nouvelle-Zélande',away:'Belgique',      stadium:'BC Place',                 city:'Vancouver', time:'17h00'},
  {id:43,group:'H',date:'15 juin',day:'Lun',home:'Espagne',      away:'Cap-Vert',         stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'20h00'},
  {id:44,group:'H',date:'15 juin',day:'Lun',home:'Arabie Saoudite',away:'Uruguay',        stadium:'Hard Rock Stadium',        city:'Miami', time:'23h00'},
  {id:45,group:'H',date:'21 juin',day:'Dim',home:'Espagne',      away:'Arabie Saoudite',  stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'13h00'},
  {id:46,group:'H',date:'21 juin',day:'Dim',home:'Uruguay',      away:'Cap-Vert',         stadium:'Hard Rock Stadium',        city:'Miami', time:'16h00'},
  {id:47,group:'H',date:'26 juin',day:'Ven',home:'Cap-Vert',     away:'Arabie Saoudite',  stadium:'NRG Stadium',              city:'Houston', time:'19h00'},
  {id:48,group:'H',date:'26 juin',day:'Ven',home:'Uruguay',      away:'Espagne',          stadium:'Estadio Akron',            city:'Guadalajara',  featured:true, time:'22h00'},
  {id:49,group:'I',date:'16 juin',day:'Mar',home:'France',       away:'Sénégal',          stadium:'MetLife Stadium',          city:'New York',     featured:true, time:'15h00'},
  {id:50,group:'I',date:'16 juin',day:'Mar',home:'Irak',         away:'Norvège',          stadium:'Gillette Stadium',         city:'Boston', time:'15h00'},
  {id:51,group:'I',date:'22 juin',day:'Lun',home:'France',       away:'Irak',             stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'18h00'},
  {id:52,group:'I',date:'22 juin',day:'Lun',home:'Norvège',      away:'Sénégal',          stadium:'MetLife Stadium',          city:'New York', time:'18h00'},
  {id:53,group:'I',date:'26 juin',day:'Ven',home:'Norvège',      away:'France',           stadium:'Gillette Stadium',         city:'Boston', time:'21h00'},
  {id:54,group:'I',date:'26 juin',day:'Ven',home:'Sénégal',      away:'Irak',             stadium:'BMO Field',                city:'Toronto', time:'21h00'},
  {id:55,group:'J',date:'16 juin',day:'Mar',home:'Argentine',    away:'Algérie',          stadium:'Arrowhead Stadium',        city:'Kansas City',  featured:true, time:'16h00'},
  {id:56,group:'J',date:'16 juin',day:'Mar',home:'Autriche',     away:'Jordanie',         stadium:'Levi\'s Stadium',          city:'San Francisco', time:'16h00'},
  {id:57,group:'J',date:'22 juin',day:'Lun',home:'Argentine',    away:'Autriche',         stadium:'AT&T Stadium',             city:'Dallas', time:'19h00'},
  {id:58,group:'J',date:'22 juin',day:'Lun',home:'Jordanie',     away:'Algérie',          stadium:'Levi\'s Stadium',          city:'San Francisco', time:'19h00'},
  {id:59,group:'J',date:'27 juin',day:'Sam',home:'Jordanie',     away:'Argentine',        stadium:'AT&T Stadium',             city:'Dallas', time:'22h00'},
  {id:60,group:'J',date:'27 juin',day:'Sam',home:'Algérie',      away:'Autriche',         stadium:'Arrowhead Stadium',        city:'Kansas City', time:'22h00'},
  {id:61,group:'K',date:'17 juin',day:'Mer',home:'Portugal',     away:'RD Congo',         stadium:'NRG Stadium',              city:'Houston', time:'15h00'},
  {id:62,group:'K',date:'17 juin',day:'Mer',home:'Ouzbékistan',  away:'Colombie',         stadium:'Estadio Azteca',           city:'Mexico City', time:'15h00'},
  {id:63,group:'K',date:'23 juin',day:'Mar',home:'Portugal',     away:'Ouzbékistan',      stadium:'NRG Stadium',              city:'Houston', time:'20h00'},
  {id:64,group:'K',date:'23 juin',day:'Mar',home:'Colombie',     away:'RD Congo',         stadium:'Estadio Akron',            city:'Guadalajara', time:'20h00'},
  {id:65,group:'K',date:'27 juin',day:'Sam',home:'Colombie',     away:'Portugal',         stadium:'Hard Rock Stadium',        city:'Miami',        featured:true, time:'23h00'},
  {id:66,group:'K',date:'27 juin',day:'Sam',home:'RD Congo',     away:'Ouzbékistan',      stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'23h00'},
  {id:67,group:'L',date:'17 juin',day:'Mer',home:'Angleterre',   away:'Croatie',          stadium:'AT&T Stadium',             city:'Dallas',       featured:true, time:'17h00'},
  {id:68,group:'L',date:'17 juin',day:'Mer',home:'Ghana',        away:'Panama',           stadium:'BMO Field',                city:'Toronto', time:'17h00'},
  {id:69,group:'L',date:'23 juin',day:'Mar',home:'Angleterre',   away:'Ghana',            stadium:'Gillette Stadium',         city:'Boston', time:'19h30'},
  {id:70,group:'L',date:'23 juin',day:'Mar',home:'Panama',       away:'Croatie',          stadium:'BMO Field',                city:'Toronto', time:'19h30'},
  {id:71,group:'L',date:'27 juin',day:'Sam',home:'Panama',       away:'Angleterre',       stadium:'MetLife Stadium',          city:'New York', time:'22h00'},
  {id:72,group:'L',date:'27 juin',day:'Sam',home:'Croatie',      away:'Ghana',            stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'22h00'},
];

const GROUPS_DATA = {
  A:{teams:['Mexique','Afrique du Sud','Corée du Sud','Rép. Tchèque']},
  B:{teams:['Canada','Bosnie-Herzégovine','Qatar','Suisse']},
  C:{teams:['Brésil','Maroc','Haïti','Écosse']},
  D:{teams:['États-Unis','Paraguay','Australie','Türkiye']},
  E:{teams:['Allemagne','Curaçao','Côte d\'Ivoire','Équateur']},
  F:{teams:['Pays-Bas','Japon','Suède','Tunisie']},
  G:{teams:['Belgique','Égypte','Iran','Nouvelle-Zélande']},
  H:{teams:['Espagne','Cap-Vert','Arabie Saoudite','Uruguay']},
  I:{teams:['France','Sénégal','Irak','Norvège']},
  J:{teams:['Argentine','Algérie','Autriche','Jordanie']},
  K:{teams:['Portugal','RD Congo','Ouzbékistan','Colombie']},
  L:{teams:['Angleterre','Croatie','Ghana','Panama']},
};

const TEAM_DATA = {
  'Mexique':             { continent:'CONCACAF 🌎', participations:17, meilleur:'Quarts de finale (1970, 1986)', titres:[] },
  'Afrique du Sud':      { continent:'CAF 🌍',       participations:3,  meilleur:'1er tour (2010 — hôte)', titres:[] },
  'Corée du Sud':        { continent:'AFC 🌏',        participations:11, meilleur:'4e place (2002)', titres:[] },
  'Rép. Tchèque':            { continent:'UEFA 🌍',       participations:3,  meilleur:'Finaliste (1962 — Tchécoslovaquie)', titres:[] },
  'Canada':              { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (1986)', titres:[] },
  'Bosnie-Herzégovine':  { continent:'UEFA 🌍',       participations:2,  meilleur:'1er tour (2014)', titres:[] },
  'Qatar':               { continent:'AFC 🌏',        participations:2,  meilleur:'1er tour (2022 — hôte)', titres:[] },
  'Suisse':              { continent:'UEFA 🌍',       participations:13, meilleur:'Quarts de finale (1934, 1938, 1954)', titres:[] },
  'Brésil':              { continent:'CONMEBOL 🌎', participations:22, meilleur:'Vainqueur (×5)', titres:[1958,1962,1970,1994,2002] },
  'Maroc':               { continent:'CAF 🌍',        participations:7,  meilleur:'4e place (2022)', titres:[] },
  'Haïti':               { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (1974)', titres:[] },
  'Écosse':              { continent:'UEFA 🌍',       participations:8,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'États-Unis':          { continent:'CONCACAF 🌎', participations:11, meilleur:'3e place (1930)', titres:[] },
  'Paraguay':            { continent:'CONMEBOL 🌎', participations:9,  meilleur:'Quarts de finale (1954, 2010)', titres:[] },
  'Australie':           { continent:'AFC 🌏',        participations:6,  meilleur:'Quarts de finale (2006)', titres:[] },
  'Türkiye':             { continent:'UEFA 🌍',       participations:3,  meilleur:'3e place (2002)', titres:[] },
  'Allemagne':           { continent:'UEFA 🌍',       participations:20, meilleur:'Vainqueur (×4)', titres:[1954,1974,1990,2014] },
  'Curaçao':             { continent:'CONCACAF 🌎', participations:1,  meilleur:'Première participation', titres:[] },
  "Côte d'Ivoire":       { continent:'CAF 🌍',        participations:3,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Équateur':            { continent:'CONMEBOL 🌎', participations:4,  meilleur:'Huitièmes de finale (2006)', titres:[] },
  'Pays-Bas':            { continent:'UEFA 🌍',       participations:11, meilleur:'Finaliste (1974, 1978, 2010)', titres:[] },
  'Japon':               { continent:'AFC 🌏',        participations:8,  meilleur:'Huitièmes de finale (2002, 2010, 2018, 2022)', titres:[] },
  'Suède':               { continent:'UEFA 🌍',       participations:12, meilleur:'Finaliste (1958), 3e place (1950, 1994)', titres:[] },
  'Tunisie':             { continent:'CAF 🌍',        participations:6,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Belgique':            { continent:'UEFA 🌍',       participations:14, meilleur:'3e place (2018)', titres:[] },
  'Égypte':              { continent:'CAF 🌍',        participations:4,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Iran':                { continent:'AFC 🌏',        participations:7,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Nouvelle-Zélande':    { continent:'OFC 🌏',        participations:3,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Espagne':             { continent:'UEFA 🌍',       participations:16, meilleur:'Vainqueur (×1)', titres:[2010] },
  'Cap-Vert':            { continent:'CAF 🌍',        participations:1,  meilleur:'Première participation', titres:[] },
  'Arabie Saoudite':     { continent:'AFC 🌏',        participations:7,  meilleur:'Huitièmes de finale (1994)', titres:[] },
  'Uruguay':             { continent:'CONMEBOL 🌎', participations:14, meilleur:'Vainqueur (×2)', titres:[1930,1950] },
  'France':              { continent:'UEFA 🌍',       participations:16, meilleur:'Vainqueur (×2)', titres:[1998,2018] },
  'Sénégal':             { continent:'CAF 🌍',        participations:3,  meilleur:'Quarts de finale (2002)', titres:[] },
  'Irak':                { continent:'AFC 🌏',        participations:2,  meilleur:'1er tour (1986)', titres:[] },
  'Norvège':             { continent:'UEFA 🌍',       participations:3,  meilleur:'Quarts de finale (1938)', titres:[] },
  'Argentine':           { continent:'CONMEBOL 🌎', participations:19, meilleur:'Vainqueur (×3)', titres:[1978,1986,2022] },
  'Algérie':             { continent:'CAF 🌍',        participations:5,  meilleur:'Huitièmes de finale (2014)', titres:[] },
  'Autriche':            { continent:'UEFA 🌍',       participations:8,  meilleur:'3e place (1954)', titres:[] },
  'Jordanie':            { continent:'AFC 🌏',        participations:1,  meilleur:'Première participation', titres:[] },
  'Portugal':            { continent:'UEFA 🌍',       participations:9,  meilleur:'3e place (1966)', titres:[] },
  'RD Congo':            { continent:'CAF 🌍',        participations:2,  meilleur:'1er tour (1974 — sous le nom Zaïre)', titres:[] },
  'Ouzbékistan':         { continent:'AFC 🌏',        participations:1,  meilleur:'Première participation', titres:[] },
  'Colombie':            { continent:'CONMEBOL 🌎', participations:7,  meilleur:'Quarts de finale (2014)', titres:[] },
  'Angleterre':          { continent:'UEFA 🌍',       participations:17, meilleur:'Vainqueur (×1)', titres:[1966] },
  'Croatie':             { continent:'UEFA 🌍',       participations:7,  meilleur:'Finaliste (2018), 3e place (1998, 2022)', titres:[] },
  'Ghana':               { continent:'CAF 🌍',        participations:4,  meilleur:'Quarts de finale (2010)', titres:[] },
  'Panama':              { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (2018)', titres:[] },
};

const HAITI_MATCHES = [
  { id:14, date:'13 juin', home:'Haïti', away:'Écosse',  time:'21h00' },
  { id:16, date:'19 juin', home:'Brésil', away:'Haïti',  time:'20h30' },
  { id:18, date:'24 juin', home:'Maroc',  away:'Haïti',  time:'21h00' },
];

