// ─── DONNÉES STATIQUES ─────────────────────────────────

const FLAGS = {
  'Mexique':'🇲🇽','Afrique du Sud':'🇿🇦','Corée du Sud':'🇰🇷','Rép. Tchèque':'🇨🇿',
  'Canada':'🇨🇦','Qatar':'🇶🇦','Bosnie-Herzégovine':'🇧🇦','Suisse':'🇨🇭',
  'Brésil':'🇧🇷','Écosse':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Maroc':'🇲🇦','Haïti':'🇭🇹',
  'États-Unis':'🇺🇸','Türkiye':'🇹🇷','Paraguay':'🇵🇾','Australie':'🇦🇺',
  'Allemagne':'🇩🇪','Équateur':'🇪🇨','Côte d\'Ivoire':'🇨🇮','Curaçao':'🇨🇼',
  'Pays-Bas':'🇳🇱','Tunisie':'🇹🇳','Japon':'🇯🇵','Suède':'🇸🇪',
  'Belgique':'🇧🇪','Nouvelle-Zélande':'🇳🇿','Égypte':'🇪🇬','Iran':'🇮🇷',
  'Espagne':'🇪🇸','Cap-Vert':'🇨🇻','Uruguay':'🇺🇾','Arabie Saoudite':'🇸🇦',
  'France':'🇫🇷','Irak':'🇮🇶','Sénégal':'🇸🇳','Norvège':'🇳🇴',
  'Argentine':'🇦🇷','Jordanie':'🇯🇴','Algérie':'🇩🇿','Autriche':'🇦🇹',
  'Portugal':'🇵🇹','RD Congo':'🇨🇩','Colombie':'🇨🇴','Ouzbékistan':'🇺🇿',
  'Angleterre':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Panama':'🇵🇦','Croatie':'🇭🇷','Ghana':'🇬🇭',
};

const GROUP_COLORS = {
  A:'#e74c3c',B:'#e67e22',C:'#f1c40f',D:'#2ecc71',
  E:'#1abc9c',F:'#3498db',G:'#9b59b6',H:'#e91e8c',
  I:'#ff5722',J:'#4caf50',K:'#00bcd4',L:'#ff9800',
  'KO':'#7c3aed'
};

const FEATURED = [
  'France vs Sénégal','Argentine vs Algérie','Portugal vs Colombie',
  'Brésil vs Maroc','Espagne vs Uruguay','Pays-Bas vs Japon',
  'Angleterre vs Croatie','États-Unis vs Turquie','Mexique vs Afrique du Sud'
];

const MATCHES = [
  {id:1, group:'A',date:'11 juin',day:'Jeu',home:'Mexique',      away:'Afrique du Sud',   stadium:'Estadio Azteca',           city:'Mexico City',  featured:true, label:'OUVERTURE', time:'15h00'},
  {id:2, group:'A',date:'11 juin',day:'Jeu',home:'Corée du Sud', away:'Rép. Tchèque',         stadium:'Estadio Akron',            city:'Guadalajara', time:'22h00'},
  {id:3, group:'A',date:'18 juin',day:'Jeu',home:'Rép. Tchèque',     away:'Afrique du Sud',   stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'15h00'},
  {id:4, group:'A',date:'18 juin',day:'Jeu',home:'Mexique',      away:'Corée du Sud',     stadium:'Estadio Akron',            city:'Guadalajara', time:'21h00'},
  {id:5, group:'A',date:'24 juin',day:'Mer',home:'Rép. Tchèque',     away:'Mexique',          stadium:'Estadio Azteca',           city:'Mexico City', time:'15h00'},
  {id:6, group:'A',date:'24 juin',day:'Mer',home:'Afrique du Sud',away:'Corée du Sud',    stadium:'Estadio BBVA',             city:'Monterrey', time:'18h00'},
  {id:7, group:'B',date:'12 juin',day:'Ven',home:'Canada',       away:'Bosnie-Herzégovine',stadium:'BMO Field',               city:'Toronto', time:'21h00'},
  {id:8, group:'B',date:'13 juin',day:'Sam',home:'Qatar',        away:'Suisse',           stadium:'Levi\'s Stadium',          city:'San Francisco', time:'12h00'},
  {id:9, group:'B',date:'18 juin',day:'Jeu',home:'Suisse',       away:'Bosnie-Herzégovine',stadium:'SoFi Stadium',            city:'Los Angeles', time:'13h00'},
  {id:10,group:'B',date:'18 juin',day:'Jeu',home:'Canada',       away:'Qatar',            stadium:'BC Place',                 city:'Vancouver', time:'16h00'},
  {id:11,group:'B',date:'24 juin',day:'Mer',home:'Suisse',       away:'Canada',           stadium:'BC Place',                 city:'Vancouver', time:'19h00'},
  {id:12,group:'B',date:'24 juin',day:'Mer',home:'Bosnie-Herzégovine',away:'Qatar',       stadium:'Lumen Field',              city:'Seattle', time:'22h00'},
  {id:13,group:'C',date:'13 juin',day:'Sam',home:'Brésil',       away:'Maroc',            stadium:'MetLife Stadium',          city:'New York',     featured:true, time:'12h00'},
  {id:14,group:'C',date:'13 juin',day:'Sam',home:'Haïti',        away:'Écosse',           stadium:'Gillette Stadium',         city:'Boston', time:'21h00'},
  {id:15,group:'C',date:'19 juin',day:'Ven',home:'Écosse',       away:'Maroc',            stadium:'Gillette Stadium',         city:'Boston', time:'18h00'},
  {id:16,group:'C',date:'19 juin',day:'Ven',home:'Brésil',       away:'Haïti',            stadium:'Lincoln Financial Field',  city:'Philadelphie', featured:true, time:'20h30'},
  {id:17,group:'C',date:'24 juin',day:'Mer',home:'Écosse',       away:'Brésil',           stadium:'Hard Rock Stadium',        city:'Miami', time:'15h00'},
  {id:18,group:'C',date:'24 juin',day:'Mer',home:'Maroc',        away:'Haïti',            stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'18h00'},
  {id:19,group:'D',date:'12 juin',day:'Ven',home:'États-Unis',   away:'Paraguay',         stadium:'SoFi Stadium',             city:'Los Angeles',  featured:true, time:'21h00'},
  {id:20,group:'D',date:'13 juin',day:'Sam',home:'Australie',    away:'Türkiye',          stadium:'BC Place',                 city:'Vancouver', time:'00h00'},
  {id:21,group:'D',date:'19 juin',day:'Ven',home:'Türkiye',      away:'Paraguay',         stadium:'Levi\'s Stadium',          city:'San Francisco', time:'13h00'},
  {id:22,group:'D',date:'19 juin',day:'Ven',home:'États-Unis',   away:'Australie',        stadium:'Lumen Field',              city:'Seattle', time:'16h00'},
  {id:23,group:'D',date:'25 juin',day:'Mer',home:'Türkiye',      away:'États-Unis',       stadium:'SoFi Stadium',             city:'Los Angeles', time:'19h00'},
  {id:24,group:'D',date:'25 juin',day:'Mer',home:'Paraguay',     away:'Australie',        stadium:'Levi\'s Stadium',          city:'San Francisco', time:'22h00'},
  {id:25,group:'E',date:'14 juin',day:'Dim',home:'Allemagne',    away:'Curaçao',          stadium:'NRG Stadium',              city:'Houston', time:'12h00'},
  {id:26,group:'E',date:'14 juin',day:'Dim',home:'Côte d\'Ivoire',away:'Équateur',        stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'15h00'},
  {id:27,group:'E',date:'20 juin',day:'Sam',home:'Allemagne',    away:'Côte d\'Ivoire',   stadium:'BMO Field',                city:'Toronto', time:'18h00'},
  {id:28,group:'E',date:'20 juin',day:'Sam',home:'Équateur',     away:'Curaçao',          stadium:'Arrowhead Stadium',        city:'Kansas City', time:'21h00'},
  {id:29,group:'E',date:'25 juin',day:'Jeu',home:'Curaçao',      away:'Côte d\'Ivoire',   stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'15h00'},
  {id:30,group:'E',date:'25 juin',day:'Jeu',home:'Équateur',     away:'Allemagne',        stadium:'MetLife Stadium',          city:'New York', time:'18h00'},
  {id:31,group:'F',date:'14 juin',day:'Dim',home:'Pays-Bas',     away:'Japon',            stadium:'AT&T Stadium',             city:'Dallas',       featured:true, time:'20h30'},
  {id:32,group:'F',date:'14 juin',day:'Dim',home:'Suède',        away:'Tunisie',          stadium:'Estadio BBVA',             city:'Monterrey', time:'23h00'},
  {id:33,group:'F',date:'20 juin',day:'Sam',home:'Pays-Bas',     away:'Suède',            stadium:'NRG Stadium',              city:'Houston', time:'13h00'},
  {id:34,group:'F',date:'20 juin',day:'Sam',home:'Tunisie',      away:'Japon',            stadium:'Estadio BBVA',             city:'Monterrey', time:'16h00'},
  {id:35,group:'F',date:'25 juin',day:'Jeu',home:'Japon',        away:'Suède',            stadium:'AT&T Stadium',             city:'Dallas', time:'20h00'},
  {id:36,group:'F',date:'25 juin',day:'Jeu',home:'Tunisie',      away:'Pays-Bas',         stadium:'Arrowhead Stadium',        city:'Kansas City', time:'00h00'},
  {id:37,group:'G',date:'15 juin',day:'Lun',home:'Belgique',     away:'Égypte',           stadium:'Lumen Field',              city:'Seattle', time:'12h00'},
  {id:38,group:'G',date:'15 juin',day:'Lun',home:'Iran',         away:'Nouvelle-Zélande', stadium:'SoFi Stadium',             city:'Los Angeles', time:'15h00'},
  {id:39,group:'G',date:'21 juin',day:'Dim',home:'Belgique',     away:'Iran',             stadium:'SoFi Stadium',             city:'Los Angeles', time:'18h00'},
  {id:40,group:'G',date:'21 juin',day:'Dim',home:'Nouvelle-Zélande',away:'Égypte',        stadium:'BC Place',                 city:'Vancouver', time:'21h00'},
  {id:41,group:'G',date:'26 juin',day:'Ven',home:'Égypte',       away:'Iran',             stadium:'Lumen Field',              city:'Seattle', time:'13h00'},
  {id:42,group:'G',date:'26 juin',day:'Ven',home:'Nouvelle-Zélande',away:'Belgique',      stadium:'BC Place',                 city:'Vancouver', time:'17h00'},
  {id:43,group:'H',date:'15 juin',day:'Lun',home:'Espagne',      away:'Cap-Vert',         stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'20h00'},
  {id:44,group:'H',date:'15 juin',day:'Lun',home:'Arabie Saoudite',away:'Uruguay',        stadium:'Hard Rock Stadium',        city:'Miami', time:'23h00'},
  {id:45,group:'H',date:'21 juin',day:'Dim',home:'Espagne',      away:'Arabie Saoudite',  stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'13h00'},
  {id:46,group:'H',date:'21 juin',day:'Dim',home:'Uruguay',      away:'Cap-Vert',         stadium:'Hard Rock Stadium',        city:'Miami', time:'16h00'},
  {id:47,group:'H',date:'26 juin',day:'Ven',home:'Cap-Vert',     away:'Arabie Saoudite',  stadium:'NRG Stadium',              city:'Houston', time:'19h00'},
  {id:48,group:'H',date:'26 juin',day:'Ven',home:'Uruguay',      away:'Espagne',          stadium:'Estadio Akron',            city:'Guadalajara',  featured:true, time:'22h00'},
  {id:49,group:'I',date:'16 juin',day:'Mar',home:'France',       away:'Sénégal',          stadium:'MetLife Stadium',          city:'New York',     featured:true, time:'15h00'},
  {id:50,group:'I',date:'16 juin',day:'Mar',home:'Irak',         away:'Norvège',          stadium:'Gillette Stadium',         city:'Boston', time:'15h00'},
  {id:51,group:'I',date:'22 juin',day:'Lun',home:'France',       away:'Irak',             stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'18h00'},
  {id:52,group:'I',date:'22 juin',day:'Lun',home:'Norvège',      away:'Sénégal',          stadium:'MetLife Stadium',          city:'New York', time:'18h00'},
  {id:53,group:'I',date:'26 juin',day:'Ven',home:'Norvège',      away:'France',           stadium:'Gillette Stadium',         city:'Boston', time:'21h00'},
  {id:54,group:'I',date:'26 juin',day:'Ven',home:'Sénégal',      away:'Irak',             stadium:'BMO Field',                city:'Toronto', time:'21h00'},
  {id:55,group:'J',date:'16 juin',day:'Mar',home:'Argentine',    away:'Algérie',          stadium:'Arrowhead Stadium',        city:'Kansas City',  featured:true, time:'16h00'},
  {id:56,group:'J',date:'16 juin',day:'Mar',home:'Autriche',     away:'Jordanie',         stadium:'Levi\'s Stadium',          city:'San Francisco', time:'16h00'},
  {id:57,group:'J',date:'22 juin',day:'Lun',home:'Argentine',    away:'Autriche',         stadium:'AT&T Stadium',             city:'Dallas', time:'19h00'},
  {id:58,group:'J',date:'22 juin',day:'Lun',home:'Jordanie',     away:'Algérie',          stadium:'Levi\'s Stadium',          city:'San Francisco', time:'19h00'},
  {id:59,group:'J',date:'27 juin',day:'Sam',home:'Jordanie',     away:'Argentine',        stadium:'AT&T Stadium',             city:'Dallas', time:'22h00'},
  {id:60,group:'J',date:'27 juin',day:'Sam',home:'Algérie',      away:'Autriche',         stadium:'Arrowhead Stadium',        city:'Kansas City', time:'22h00'},
  {id:61,group:'K',date:'17 juin',day:'Mer',home:'Portugal',     away:'RD Congo',         stadium:'NRG Stadium',              city:'Houston', time:'15h00'},
  {id:62,group:'K',date:'17 juin',day:'Mer',home:'Ouzbékistan',  away:'Colombie',         stadium:'Estadio Azteca',           city:'Mexico City', time:'15h00'},
  {id:63,group:'K',date:'23 juin',day:'Mar',home:'Portugal',     away:'Ouzbékistan',      stadium:'NRG Stadium',              city:'Houston', time:'20h00'},
  {id:64,group:'K',date:'23 juin',day:'Mar',home:'Colombie',     away:'RD Congo',         stadium:'Estadio Akron',            city:'Guadalajara', time:'20h00'},
  {id:65,group:'K',date:'27 juin',day:'Sam',home:'Colombie',     away:'Portugal',         stadium:'Hard Rock Stadium',        city:'Miami',        featured:true, time:'23h00'},
  {id:66,group:'K',date:'27 juin',day:'Sam',home:'RD Congo',     away:'Ouzbékistan',      stadium:'Mercedes-Benz Stadium',    city:'Atlanta', time:'23h00'},
  {id:67,group:'L',date:'17 juin',day:'Mer',home:'Angleterre',   away:'Croatie',          stadium:'AT&T Stadium',             city:'Dallas',       featured:true, time:'17h00'},
  {id:68,group:'L',date:'17 juin',day:'Mer',home:'Ghana',        away:'Panama',           stadium:'BMO Field',                city:'Toronto', time:'17h00'},
  {id:69,group:'L',date:'23 juin',day:'Mar',home:'Angleterre',   away:'Ghana',            stadium:'Gillette Stadium',         city:'Boston', time:'19h30'},
  {id:70,group:'L',date:'23 juin',day:'Mar',home:'Panama',       away:'Croatie',          stadium:'BMO Field',                city:'Toronto', time:'19h30'},
  {id:71,group:'L',date:'27 juin',day:'Sam',home:'Panama',       away:'Angleterre',       stadium:'MetLife Stadium',          city:'New York', time:'22h00'},
  {id:72,group:'L',date:'27 juin',day:'Sam',home:'Croatie',      away:'Ghana',            stadium:'Lincoln Financial Field',  city:'Philadelphie', time:'22h00'},
];

const GROUPS_DATA = {
  A:{teams:['Mexique','Afrique du Sud','Corée du Sud','Rép. Tchèque']},
  B:{teams:['Canada','Bosnie-Herzégovine','Qatar','Suisse']},
  C:{teams:['Brésil','Maroc','Haïti','Écosse']},
  D:{teams:['États-Unis','Paraguay','Australie','Türkiye']},
  E:{teams:['Allemagne','Curaçao','Côte d\'Ivoire','Équateur']},
  F:{teams:['Pays-Bas','Japon','Suède','Tunisie']},
  G:{teams:['Belgique','Égypte','Iran','Nouvelle-Zélande']},
  H:{teams:['Espagne','Cap-Vert','Arabie Saoudite','Uruguay']},
  I:{teams:['France','Sénégal','Irak','Norvège']},
  J:{teams:['Argentine','Algérie','Autriche','Jordanie']},
  K:{teams:['Portugal','RD Congo','Ouzbékistan','Colombie']},
  L:{teams:['Angleterre','Croatie','Ghana','Panama']},
};

const TEAM_DATA = {
  'Mexique':             { continent:'CONCACAF 🌎', participations:17, meilleur:'Quarts de finale (1970, 1986)', titres:[] , stars:[{"nom":"Hirving Lozano","club":"PSV"},{"nom":"Santiago Giménez","club":"Feyenoord"},{"nom":"Edson Álvarez","club":"West Ham"}], buteurs:[{"nom":"Javier Hernandez","buts":52},{"nom":"Cuauhtémoc Blanco","buts":38},{"nom":"Luis Hernandez","buts":35}], passeurs:[{"nom":"Cuauhtémoc Blanco","passes":45},{"nom":"Pavel Pardo","passes":32},{"nom":"Andrés Guardado","passes":30}]},
  'Afrique du Sud':      { continent:'CAF 🌍',       participations:3,  meilleur:'1er tour (2010 — hôte)', titres:[] , stars:[{"nom":"Percy Tau","club":"Al Ahly"},{"nom":"Ronwen Williams","club":"Mamelodi Sundowns"},{"nom":"Themba Zwane","club":"Mamelodi Sundowns"}], buteurs:[{"nom":"Benni McCarthy","buts":31},{"nom":"Shaun Bartlett","buts":28},{"nom":"Phil Masinga","buts":18}], passeurs:[{"nom":"Steven Pienaar","passes":25},{"nom":"Siyabonga Nomvethe","passes":18},{"nom":"Quinton Fortune","passes":15}]},
  'Corée du Sud':        { continent:'AFC 🌏',        participations:11, meilleur:'4e place (2002)', titres:[] , stars:[{"nom":"Son Heung-min","club":"Tottenham"},{"nom":"Lee Kang-in","club":"PSG"},{"nom":"Kim Min-jae","club":"Bayern Munich"}], buteurs:[{"nom":"Cha Bum-kun","buts":58},{"nom":"Son Heung-min","buts":42},{"nom":"Park Ji-sung","buts":13}], passeurs:[{"nom":"Park Ji-sung","passes":28},{"nom":"Son Heung-min","passes":35},{"nom":"Lee Young-pyo","passes":20}]},
  'Rép. Tchèque':            { continent:'UEFA 🌍',       participations:3,  meilleur:'Finaliste (1962 — Tchécoslovaquie)', titres:[] , stars:[{"nom":"Patrik Schick","club":"Bayer Leverkusen"},{"nom":"Tomáš Souček","club":"West Ham"},{"nom":"Vladimír Coufal","club":"West Ham"}], buteurs:[{"nom":"Jan Koller","buts":55},{"nom":"Patrik Berger","buts":18},{"nom":"Patrik Schick","buts":30}], passeurs:[{"nom":"Pavel Nedvěd","passes":35},{"nom":"Tomáš Rosický","passes":30},{"nom":"Karel Poborský","passes":25}]},
  'Canada':              { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (1986)', titres:[] , stars:[{"nom":"Alphonso Davies","club":"Bayern Munich"},{"nom":"Jonathan David","club":"LOSC Lille"},{"nom":"Tajon Buchanan","club":"Inter Milan"}], buteurs:[{"nom":"Dwayne De Rosario","buts":22},{"nom":"Jonathan David","buts":32},{"nom":"Cyle Larin","buts":26}], passeurs:[{"nom":"Alphonso Davies","passes":25},{"nom":"Atiba Hutchinson","passes":28},{"nom":"Scott Arfield","passes":15}]},
  'Bosnie-Herzégovine':  { continent:'UEFA 🌍',       participations:2,  meilleur:'1er tour (2014)', titres:[] , stars:[{"nom":"Edin Džeko","club":"Fenerbahçe"},{"nom":"Miralem Pjanić","club":"retraité"},{"nom":"Sead Kolašinac","club":"Marseille"}], buteurs:[{"nom":"Edin Džeko","buts":63},{"nom":"Elvir Bolić","buts":22},{"nom":"Vedad Ibišević","buts":20}], passeurs:[{"nom":"Miralem Pjanić","passes":38},{"nom":"Edin Džeko","passes":28},{"nom":"Hasan Salihamidžić","passes":18}]},
  'Qatar':               { continent:'AFC 🌏',        participations:2,  meilleur:'1er tour (2022 — hôte)', titres:[] , stars:[{"nom":"Akram Afif","club":"Al-Sadd"},{"nom":"Almoez Ali","club":"Al-Duhail"},{"nom":"Hassan Al-Haydos","club":"Al-Sadd"}], buteurs:[{"nom":"Almoez Ali","buts":42},{"nom":"Hassan Al-Haydos","buts":38},{"nom":"Sebastián Soria","buts":28}], passeurs:[{"nom":"Hassan Al-Haydos","passes":30},{"nom":"Akram Afif","passes":25},{"nom":"Khalfan Ibrahim","passes":20}]},
  'Suisse':              { continent:'UEFA 🌍',       participations:13, meilleur:'Quarts de finale (1934, 1938, 1954)', titres:[] , stars:[{"nom":"Granit Xhaka","club":"Bayer Leverkusen"},{"nom":"Xherdan Shaqiri","club":"Chicago Fire"},{"nom":"Yann Sommer","club":"Inter Milan"}], buteurs:[{"nom":"Alexander Frei","buts":42},{"nom":"Kubilay Türkyilmaz","buts":34},{"nom":"Xherdan Shaqiri","buts":32}], passeurs:[{"nom":"Granit Xhaka","passes":30},{"nom":"Xherdan Shaqiri","passes":35},{"nom":"Blaise Nkufo","passes":20}]},
  'Brésil':              { continent:'CONMEBOL 🌎', participations:22, meilleur:'Vainqueur (×5)', titres:[1958,1962,1970,1994,2002] , stars:[{"nom":"Vinícius Jr.","club":"Real Madrid"},{"nom":"Rodrygo","club":"Real Madrid"},{"nom":"Endrick","club":"Real Madrid"}], buteurs:[{"nom":"Ronaldo","buts":62},{"nom":"Pelé","buts":77},{"nom":"Romário","buts":55}], passeurs:[{"nom":"Pelé","passes":53},{"nom":"Ronaldinho","passes":40},{"nom":"Kaká","passes":36}]},
  'Maroc':               { continent:'CAF 🌍',        participations:7,  meilleur:'4e place (2022)', titres:[] , stars:[{"nom":"Achraf Hakimi","club":"PSG"},{"nom":"Hakim Ziyech","club":"Galatasaray"},{"nom":"Sofiane Boufal","club":"Southampton"}], buteurs:[{"nom":"Hicham Zerouali","buts":18},{"nom":"Salaheddine Bassir","buts":16},{"nom":"Youssef En-Nesyri","buts":18}], passeurs:[{"nom":"Mustapha Hadji","passes":22},{"nom":"Hakim Ziyech","passes":25},{"nom":"Achraf Hakimi","passes":20}]},
  'Haïti':               { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (1974)', titres:[] },
  'Écosse':              { continent:'UEFA 🌍',       participations:8,  meilleur:'1er tour (jamais dépassé)', titres:[] , stars:[{"nom":"Andrew Robertson","club":"Liverpool"},{"nom":"Scott McTominay","club":"Napoli"},{"nom":"Kieran Tierney","club":"Real Sociedad"}], buteurs:[{"nom":"Denis Law","buts":30},{"nom":"Kenny Dalglish","buts":30},{"nom":"Ally McCoist","buts":19}], passeurs:[{"nom":"Kenny Dalglish","passes":28},{"nom":"Barry Ferguson","passes":22},{"nom":"Scott McTominay","passes":15}]},
  'États-Unis':          { continent:'CONCACAF 🌎', participations:11, meilleur:'3e place (1930)', titres:[] , stars:[{"nom":"Christian Pulisic","club":"AC Milan"},{"nom":"Weston McKennie","club":"Juventus"},{"nom":"Tyler Adams","club":"Bournemouth"}], buteurs:[{"nom":"Landon Donovan","buts":57},{"nom":"Clint Dempsey","buts":57},{"nom":"Brian McBride","buts":30}], passeurs:[{"nom":"Landon Donovan","passes":58},{"nom":"Claudio Reyna","passes":30},{"nom":"Christian Pulisic","passes":28}]},
  'Paraguay':            { continent:'CONMEBOL 🌎', participations:9,  meilleur:'Quarts de finale (1954, 2010)', titres:[] },
  'Australie':           { continent:'AFC 🌏',        participations:6,  meilleur:'Quarts de finale (2006)', titres:[] , stars:[{"nom":"Mat Ryan","club":"Real Sociedad"},{"nom":"Mitchell Duke","club":"Fagiano Okayama"},{"nom":"Ajdin Hrustic","club":"Hellas Verona"}], buteurs:[{"nom":"Tim Cahill","buts":50},{"nom":"John Aloisi","buts":27},{"nom":"Harry Kewell","buts":17}], passeurs:[{"nom":"Harry Kewell","passes":25},{"nom":"Tim Cahill","passes":20},{"nom":"Mark Viduka","passes":18}]},
  'Türkiye':             { continent:'UEFA 🌍',       participations:3,  meilleur:'3e place (2002)', titres:[] },
  'Allemagne':           { continent:'UEFA 🌍',       participations:20, meilleur:'Vainqueur (×4)', titres:[1954,1974,1990,2014] , stars:[{"nom":"Florian Wirtz","club":"Bayer Leverkusen"},{"nom":"Jamal Musiala","club":"Bayern Munich"},{"nom":"Antonio Rüdiger","club":"Real Madrid"}], buteurs:[{"nom":"Miroslav Klose","buts":71},{"nom":"Gerd Müller","buts":68},{"nom":"Lukas Podolski","buts":49}], passeurs:[{"nom":"Lothar Matthäus","passes":40},{"nom":"Michael Ballack","passes":35},{"nom":"Mesut Özil","passes":40}]},
  'Curaçao':             { continent:'CONCACAF 🌎', participations:1,  meilleur:'Première participation', titres:[] },
  "Côte d'Ivoire":       { continent:'CAF 🌍',        participations:3,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Équateur':            { continent:'CONMEBOL 🌎', participations:4,  meilleur:'Huitièmes de finale (2006)', titres:[] },
  'Pays-Bas':            { continent:'UEFA 🌍',       participations:11, meilleur:'Finaliste (1974, 1978, 2010)', titres:[] , stars:[{"nom":"Virgil van Dijk","club":"Liverpool"},{"nom":"Cody Gakpo","club":"Liverpool"},{"nom":"Xavi Simons","club":"RB Leipzig"}], buteurs:[{"nom":"Patrick Kluivert","buts":40},{"nom":"Ruud van Nistelrooy","buts":35},{"nom":"Robin van Persie","buts":50}], passeurs:[{"nom":"Johan Cruyff","passes":42},{"nom":"Dennis Bergkamp","passes":37},{"nom":"Wesley Sneijder","passes":35}]},
  'Japon':               { continent:'AFC 🌏',        participations:8,  meilleur:'Huitièmes de finale (2002, 2010, 2018, 2022)', titres:[] , stars:[{"nom":"Takefusa Kubo","club":"Real Sociedad"},{"nom":"Kaoru Mitoma","club":"Brighton"},{"nom":"Ritsu Doan","club":"Freiburg"}], buteurs:[{"nom":"Kunishige Kamamoto","buts":75},{"nom":"Shinji Okazaki","buts":50},{"nom":"Keisuke Honda","buts":37}], passeurs:[{"nom":"Keisuke Honda","passes":37},{"nom":"Shunsuke Nakamura","passes":30},{"nom":"Hidetoshi Nakata","passes":28}]},
  'Suède':               { continent:'UEFA 🌍',       participations:12, meilleur:'Finaliste (1958), 3e place (1950, 1994)', titres:[] },
  'Tunisie':             { continent:'CAF 🌍',        participations:6,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Belgique':            { continent:'UEFA 🌍',       participations:14, meilleur:'3e place (2018)', titres:[] , stars:[{"nom":"Kevin De Bruyne","club":"Manchester City"},{"nom":"Romelu Lukaku","club":"AS Roma"},{"nom":"Lois Openda","club":"RB Leipzig"}], buteurs:[{"nom":"Romelu Lukaku","buts":85},{"nom":"Eden Hazard","buts":33},{"nom":"Kevin De Bruyne","buts":26}], passeurs:[{"nom":"Kevin De Bruyne","passes":55},{"nom":"Eden Hazard","passes":40},{"nom":"Jan Vertonghen","passes":25}]},
  'Égypte':              { continent:'CAF 🌍',        participations:4,  meilleur:'1er tour (jamais dépassé)', titres:[] },
  'Iran':                { continent:'AFC 🌏',        participations:7,  meilleur:'1er tour (jamais dépassé)', titres:[] , stars:[{"nom":"Sardar Azmoun","club":"Bayer Leverkusen"},{"nom":"Mehdi Taremi","club":"Inter Milan"},{"nom":"Alireza Jahanbakhsh","club":"Feyenoord"}], buteurs:[{"nom":"Ali Daei","buts":109},{"nom":"Mehdi Taremi","buts":48},{"nom":"Karim Bagheri","buts":50}], passeurs:[{"nom":"Karim Bagheri","passes":35},{"nom":"Javad Nekounam","passes":30},{"nom":"Mehdi Taremi","passes":25}]},
  'Nouvelle-Zélande':    { continent:'OFC 🌏',        participations:3,  meilleur:'1er tour (jamais dépassé)', titres:[] , stars:[{"nom":"Chris Wood","club":"Nottingham Forest"},{"nom":"Clayton Lewis","club":"Udinese"},{"nom":"Joe Bell","club":"Nashville SC"}], buteurs:[{"nom":"Vaughan Coveny","buts":28},{"nom":"Chris Wood","buts":32},{"nom":"Steve Sumner","buts":22}], passeurs:[{"nom":"Ryan Nelsen","passes":20},{"nom":"Chris Wood","passes":15},{"nom":"Simon Elliott","passes":14}]},
  'Espagne':             { continent:'UEFA 🌍',       participations:16, meilleur:'Vainqueur (×1)', titres:[2010] , stars:[{"nom":"Pedri","club":"FC Barcelona"},{"nom":"Lamine Yamal","club":"FC Barcelona"},{"nom":"Rodri","club":"Manchester City"}], buteurs:[{"nom":"David Villa","buts":59},{"nom":"Raúl","buts":44},{"nom":"Fernando Torres","buts":38}], passeurs:[{"nom":"Xavi Hernández","passes":52},{"nom":"Andrés Iniesta","passes":35},{"nom":"David Silva","passes":40}]},
  'Cap-Vert':            { continent:'CAF 🌍',        participations:1,  meilleur:'Première participation', titres:[] },
  'Arabie Saoudite':     { continent:'AFC 🌏',        participations:7,  meilleur:'Huitièmes de finale (1994)', titres:[] , stars:[{"nom":"Salem Al-Dawsari","club":"Al-Hilal"},{"nom":"Mohammed Al-Owais","club":"Al-Hilal"},{"nom":"Firas Al-Buraikan","club":"Al-Fateh"}], buteurs:[{"nom":"Yasser Al-Qahtani","buts":46},{"nom":"Sami Al-Jaber","buts":44},{"nom":"Salem Al-Dawsari","buts":25}], passeurs:[{"nom":"Sami Al-Jaber","passes":30},{"nom":"Yasser Al-Qahtani","passes":28},{"nom":"Nawaf Al-Temyat","passes":22}]},
  'Uruguay':             { continent:'CONMEBOL 🌎', participations:14, meilleur:'Vainqueur (×2)', titres:[1930,1950] , stars:[{"nom":"Darwin Núñez","club":"Liverpool"},{"nom":"Federico Valverde","club":"Real Madrid"},{"nom":"Ronald Araújo","club":"FC Barcelona"}], buteurs:[{"nom":"Luis Suárez","buts":68},{"nom":"Diego Forlán","buts":36},{"nom":"Óscar Míguez","buts":28}], passeurs:[{"nom":"Diego Forlán","passes":25},{"nom":"Luis Suárez","passes":35},{"nom":"Enzo Francescoli","passes":30}]},
  'France':              { continent:'UEFA 🌍',       participations:16, meilleur:'Vainqueur (×2)', titres:[1998,2018] , stars:[{"nom":"Kylian Mbappé","club":"Real Madrid"},{"nom":"Antoine Griezmann","club":"Atlético Madrid"},{"nom":"Aurélien Tchouaméni","club":"Real Madrid"}], buteurs:[{"nom":"Thierry Henry","buts":51},{"nom":"Michel Platini","buts":41},{"nom":"Kylian Mbappé","buts":48}], passeurs:[{"nom":"Zinedine Zidane","passes":36},{"nom":"Michel Platini","passes":38},{"nom":"Thierry Henry","passes":35}]},
  'Sénégal':             { continent:'CAF 🌍',        participations:3,  meilleur:'Quarts de finale (2002)', titres:[] , stars:[{"nom":"Sadio Mané","club":"Al Nassr"},{"nom":"Édouard Mendy","club":"Al Ahli"},{"nom":"Ismaïla Sarr","club":"Crystal Palace"}], buteurs:[{"nom":"Sadio Mané","buts":38},{"nom":"Henri Camara","buts":29},{"nom":"Moussa Sow","buts":22}], passeurs:[{"nom":"Sadio Mané","passes":28},{"nom":"Cheikhou Kouyaté","passes":18},{"nom":"Papa Bouba Diop","passes":15}]},
  'Irak':                { continent:'AFC 🌏',        participations:2,  meilleur:'1er tour (1986)', titres:[] },
  'Norvège':             { continent:'UEFA 🌍',       participations:3,  meilleur:'Quarts de finale (1938)', titres:[] },
  'Argentine':           { continent:'CONMEBOL 🌎', participations:19, meilleur:'Vainqueur (×3)', titres:[1978,1986,2022] , stars:[{"nom":"Lionel Messi","club":"Inter Miami"},{"nom":"Julián Álvarez","club":"Atlético Madrid"},{"nom":"Enzo Fernández","club":"Chelsea"}], buteurs:[{"nom":"Lionel Messi","buts":109},{"nom":"Gabriel Batistuta","buts":54},{"nom":"Sergio Agüero","buts":42}], passeurs:[{"nom":"Lionel Messi","passes":58},{"nom":"Diego Maradona","passes":35},{"nom":"Juan Román Riquelme","passes":30}]},
  'Algérie':             { continent:'CAF 🌍',        participations:5,  meilleur:'Huitièmes de finale (2014)', titres:[] },
  'Autriche':            { continent:'UEFA 🌍',       participations:8,  meilleur:'3e place (1954)', titres:[] , stars:[{"nom":"David Alaba","club":"Real Madrid"},{"nom":"Marcel Sabitzer","club":"Borussia Dortmund"},{"nom":"Marko Arnautović","club":"Inter Milan"}], buteurs:[{"nom":"Toni Polster","buts":44},{"nom":"Hans Krankl","buts":34},{"nom":"Marko Arnautović","buts":26}], passeurs:[{"nom":"Andreas Herzog","passes":26},{"nom":"David Alaba","passes":22},{"nom":"Ernst Happel","passes":20}]},
  'Jordanie':            { continent:'AFC 🌏',        participations:1,  meilleur:'Première participation', titres:[] , stars:[{"nom":"Yazan Al-Naimat","club":"Al-Faisaly"},{"nom":"Ahmad Hayel","club":"Al-Wehdat"},{"nom":"Musa Al-Taamari","club":"Montpellier"}], buteurs:[{"nom":"Hassan Abdel-Fattah","buts":18},{"nom":"Ahmad Hayel","buts":15},{"nom":"Musa Al-Taamari","buts":12}], passeurs:[{"nom":"Hatem Aqel","passes":20},{"nom":"Ahmad Hayel","passes":15},{"nom":"Musa Al-Taamari","passes":14}]},
  'Portugal':            { continent:'UEFA 🌍',       participations:9,  meilleur:'3e place (1966)', titres:[] , stars:[{"nom":"Cristiano Ronaldo","club":"Al Nassr"},{"nom":"Bruno Fernandes","club":"Manchester United"},{"nom":"Rafael Leão","club":"AC Milan"}], buteurs:[{"nom":"Cristiano Ronaldo","buts":135},{"nom":"Pauleta","buts":47},{"nom":"Eusébio","buts":41}], passeurs:[{"nom":"Cristiano Ronaldo","passes":45},{"nom":"Luís Figo","passes":38},{"nom":"Bruno Fernandes","passes":32}]},
  'RD Congo':            { continent:'CAF 🌍',        participations:2,  meilleur:'1er tour (1974 — sous le nom Zaïre)', titres:[] , stars:[{"nom":"Dieumerci Mbokani","club":"retraité"},{"nom":"Chancel Mbemba","club":"Marseille"},{"nom":"Yannick Bolasie","club":"Millwall"}], buteurs:[{"nom":"Shabani Nonda","buts":22},{"nom":"Dieumerci Mbokani","buts":23},{"nom":"Trésor Luntadila","buts":15}], passeurs:[{"nom":"Youssouf Mulumbu","passes":18},{"nom":"Chancel Mbemba","passes":12},{"nom":"Yannick Bolasie","passes":15}]},
  'Ouzbékistan':         { continent:'AFC 🌏',        participations:1,  meilleur:'Première participation', titres:[] , stars:[{"nom":"Eldor Shomurodov","club":"Roma"},{"nom":"Jasur Yaxshiboyev","club":"AGMK"},{"nom":"Otabek Shukurov","club":"Pakhtakor"}], buteurs:[{"nom":"Maxim Shatskikh","buts":34},{"nom":"Eldor Shomurodov","buts":22},{"nom":"Server Djeparov","buts":18}], passeurs:[{"nom":"Server Djeparov","passes":25},{"nom":"Eldor Shomurodov","passes":18},{"nom":"Timur Kapadze","passes":15}]},
  'Colombie':            { continent:'CONMEBOL 🌎', participations:7,  meilleur:'Quarts de finale (2014)', titres:[] , stars:[{"nom":"James Rodríguez","club":"Rayo Vallecano"},{"nom":"Luis Díaz","club":"Liverpool"},{"nom":"Juan Cuadrado","club":"retraité"}], buteurs:[{"nom":"Radamel Falcao","buts":36},{"nom":"Arnoldo Iguarán","buts":25},{"nom":"Carlos Bacca","buts":23}], passeurs:[{"nom":"Carlos Valderrama","passes":45},{"nom":"James Rodríguez","passes":38},{"nom":"Freddy Rincón","passes":28}]},
  'Angleterre':          { continent:'UEFA 🌍',       participations:17, meilleur:'Vainqueur (×1)', titres:[1966] , stars:[{"nom":"Harry Kane","club":"Bayern Munich"},{"nom":"Jude Bellingham","club":"Real Madrid"},{"nom":"Phil Foden","club":"Manchester City"}], buteurs:[{"nom":"Wayne Rooney","buts":53},{"nom":"Harry Kane","buts":68},{"nom":"Gary Lineker","buts":48}], passeurs:[{"nom":"David Beckham","passes":42},{"nom":"Frank Lampard","passes":38},{"nom":"Steven Gerrard","passes":35}]},
  'Croatie':             { continent:'UEFA 🌍',       participations:7,  meilleur:'Finaliste (2018), 3e place (1998, 2022)', titres:[] , stars:[{"nom":"Luka Modrić","club":"Real Madrid"},{"nom":"Ivan Perišić","club":"Hajduk Split"},{"nom":"Mateo Kovačić","club":"Manchester City"}], buteurs:[{"nom":"Davor Šuker","buts":45},{"nom":"Ivan Perišić","buts":33},{"nom":"Mario Mandžukić","buts":33}], passeurs:[{"nom":"Luka Modrić","passes":42},{"nom":"Ivan Rakitić","passes":35},{"nom":"Zvonimir Boban","passes":30}]},
  'Ghana':               { continent:'CAF 🌍',        participations:4,  meilleur:'Quarts de finale (2010)', titres:[] , stars:[{"nom":"Mohammed Kudus","club":"West Ham"},{"nom":"Thomas Partey","club":"Arsenal"},{"nom":"Jordan Ayew","club":"Leicester"}], buteurs:[{"nom":"Asamoah Gyan","buts":51},{"nom":"Abedi Pelé","buts":33},{"nom":"Tony Yeboah","buts":29}], passeurs:[{"nom":"Abedi Pelé","passes":35},{"nom":"Michael Essien","passes":22},{"nom":"André Ayew","passes":20}]},
  'Panama':              { continent:'CONCACAF 🌎', participations:2,  meilleur:'1er tour (2018)', titres:[] , stars:[{"nom":"Rolando Blackburn","club":"LD Alajuelense"},{"nom":"Adalberto Carrasquilla","club":"Houston Dynamo"},{"nom":"Édgar Bárcenas","club":"LD Alajuelense"}], buteurs:[{"nom":"Luis Tejada","buts":43},{"nom":"Rolando Fonseca","buts":28},{"nom":"Blas Pérez","buts":42}], passeurs:[{"nom":"Alberto Gaitán","passes":18},{"nom":"Amílcar Henríquez","passes":15},{"nom":"Adalberto Carrasquilla","passes":12}]},
};

const HAITI_MATCHES = [
  { id:14, date:'13 juin', home:'Haïti', away:'Écosse',  time:'21h00' },
  { id:16, date:'19 juin', home:'Brésil', away:'Haïti',  time:'20h30' },
  { id:18, date:'24 juin', home:'Maroc',  away:'Haïti',  time:'21h00' },
];

